- name: my Elk playbook
  hosts: elk
  remote_user: azureuser
  become: True
  tasks:

    # Use sysctl module
  - name: Use more memory
    sysctl:
      name: vm.max_map_count
      value: 262144
      state: present
      reload: yes
    
    # Use command module
  - name: Increase Virtual Memory
    command: sysctl -w vm.max_map_count=262144
    
    #Use apt module
  - name: Install docker.io
    apt:
      update_cache: yes
      force_apt_get: yes
      name: docker.io
      state: present

  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present
      force_apt_get: yes
    
    # Use pip module - Defaults to pip3    
  - name: Install Python Docker Module
    pip: 
      name: docker
      state: present

    # Use docker_container module
  - name: Download and Launch a docker web container
    docker_container: 
      name: elk 
      image: sebp/elk:761
      state: started
      restart_policy: always
      ports:
       - "5601:5601"
       - "9200:9200"
       - "5044:5044"

    # Use systemd module
  - name: Make sure docker is running on boot
    systemd:
      name: docker
      enabled: yes
